# This is a test repo to try github actions

name: CI

# Controls when the action will run. Triggers the workflow on push 
# events but only for the master branch

on:
  push:
    branches: [master]

jobs:
  show:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run online script
        run: echo Hello World

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.